/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppSetupRouteImport } from './routes/_app/setup'
import { Route as CatalogSectionRouteImport } from './routes/catalog.$section'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings.profile'
import { Route as AppSettingsTokensRouteImport } from './routes/_app/settings.tokens'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users.index'
import { Route as AppUsersHandleRouteImport } from './routes/_app/users.$handle'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects.$projectId.index'
import { Route as AppProjectsProjectIdJobsJobIdRouteImport } from './routes/_app/projects.$projectId.jobs.$jobId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const CatalogSectionRoute = CatalogSectionRouteImport.update({
  id: '/catalog/$section',
  path: '/catalog/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTokensRoute = AppSettingsTokensRouteImport.update({
  id: '/settings/tokens',
  path: '/settings/tokens',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersHandleRoute = AppUsersHandleRouteImport.update({
  id: '/users/$handle',
  path: '/users/$handle',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdJobsJobIdRoute =
  AppProjectsProjectIdJobsJobIdRouteImport.update({
    id: '/projects/$projectId/jobs/$jobId',
    path: '/projects/$projectId/jobs/$jobId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AppAdminRoute
  '/setup': typeof AppSetupRoute
  '/catalog/$section': typeof CatalogSectionRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/tokens': typeof AppSettingsTokensRoute
  '/users/$handle': typeof AppUsersHandleRoute
  '/users/': typeof AppUsersIndexRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/jobs/$jobId': typeof AppProjectsProjectIdJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AppAdminRoute
  '/setup': typeof AppSetupRoute
  '/catalog/$section': typeof CatalogSectionRoute
  '/': typeof AppIndexRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/tokens': typeof AppSettingsTokensRoute
  '/users/$handle': typeof AppUsersHandleRoute
  '/users': typeof AppUsersIndexRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/jobs/$jobId': typeof AppProjectsProjectIdJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/setup': typeof AppSetupRoute
  '/catalog/$section': typeof CatalogSectionRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/tokens': typeof AppSettingsTokensRoute
  '/_app/users/$handle': typeof AppUsersHandleRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/jobs/$jobId': typeof AppProjectsProjectIdJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/setup'
    | '/catalog/$section'
    | '/settings/profile'
    | '/settings/tokens'
    | '/users/$handle'
    | '/users/'
    | '/projects/$projectId/'
    | '/projects/$projectId/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/setup'
    | '/catalog/$section'
    | '/'
    | '/settings/profile'
    | '/settings/tokens'
    | '/users/$handle'
    | '/users'
    | '/projects/$projectId'
    | '/projects/$projectId/jobs/$jobId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/admin'
    | '/_app/setup'
    | '/catalog/$section'
    | '/_app/'
    | '/_app/settings/profile'
    | '/_app/settings/tokens'
    | '/_app/users/$handle'
    | '/_app/users/'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CatalogSectionRoute: typeof CatalogSectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup': {
      id: '/_app/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/catalog/$section': {
      id: '/catalog/$section'
      path: '/catalog/$section'
      fullPath: '/catalog/$section'
      preLoaderRoute: typeof CatalogSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/tokens': {
      id: '/_app/settings/tokens'
      path: '/settings/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof AppSettingsTokensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$handle': {
      id: '/_app/users/$handle'
      path: '/users/$handle'
      fullPath: '/users/$handle'
      preLoaderRoute: typeof AppUsersHandleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/jobs/$jobId': {
      id: '/_app/projects/$projectId/jobs/$jobId'
      path: '/projects/$projectId/jobs/$jobId'
      fullPath: '/projects/$projectId/jobs/$jobId'
      preLoaderRoute: typeof AppProjectsProjectIdJobsJobIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppSetupRoute: typeof AppSetupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsTokensRoute: typeof AppSettingsTokensRoute
  AppUsersHandleRoute: typeof AppUsersHandleRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdJobsJobIdRoute: typeof AppProjectsProjectIdJobsJobIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppSetupRoute: AppSetupRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsTokensRoute: AppSettingsTokensRoute,
  AppUsersHandleRoute: AppUsersHandleRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdJobsJobIdRoute: AppProjectsProjectIdJobsJobIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CatalogSectionRoute: CatalogSectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
