// Write docs/mock-diff/designs/_shared/fonts.css: the IBM Plex Sans JP faces
// the app ships (@fontsource, same version, 400 to 700), served from jsDelivr
// and with the same ascent/descent override as vite.config.ts, so mock text
// sits where the app's does. Google Fonts CSS cannot carry that override.
// Run again after bumping @fontsource/ibm-plex-sans-jp:
//   cd apps/web && bun ../../scripts/mock-fonts.mjs
import { readFile, writeFile } from "node:fs/promises";

const pkgDir = new URL(
	"../apps/web/node_modules/@fontsource/ibm-plex-sans-jp/",
	import.meta.url,
);
const out = new URL(
	"../docs/mock-diff/designs/_shared/fonts.css",
	import.meta.url,
);
// Keep in step with plexSansJpMetrics() in apps/web/vite.config.ts.
const METRICS = "ascent-override: 114%;\n  descent-override: 36%;";

const { version } = JSON.parse(
	await readFile(new URL("package.json", pkgDir), "utf8"),
);
const files = `https://cdn.jsdelivr.net/npm/@fontsource/ibm-plex-sans-jp@${version}/files/`;
const weights = await Promise.all(
	["400", "500", "600", "700"].map((w) =>
		readFile(new URL(`${w}.css`, pkgDir), "utf8"),
	),
);
const css = weights
	.join("\n")
	.replace(/^\/\*.*\*\/\n/gm, "")
	.replaceAll(
		"font-family: 'IBM Plex Sans JP';",
		`font-family: 'IBM Plex Sans JP';\n  ${METRICS}`,
	)
	// The mocks drew with display=block before; keep it so a shot never
	// catches the fallback font.
	.replaceAll("font-display: swap;", "font-display: block;")
	.replace(
		/url\(\.\/files\/([^)]+\.woff2)\) format\('woff2'\), url\([^)]+\) format\('woff'\)/g,
		`url(${files}$1) format('woff2')`,
	);

if (css.includes("./files/"))
	throw new Error("an src the rewrite did not match is left in the output");
await writeFile(
	out,
	`/* Generated by scripts/mock-fonts.mjs from @fontsource/ibm-plex-sans-jp ${version}. Do not edit. */\n${css}`,
);
console.log(`wrote ${out.pathname} (${css.length} bytes)`);
